theme: jekyll-theme-modernist
title: Tyler McCormick
description: Associate Professor <br> Department of Statistics <br> Department of Sociology <br> University of Washington
email: mailto:tylermc@uw.edu
twitter: https://twitter.com/tylermccormick 
